/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2022-05-05 16:31:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import model.User;
import java.util.ArrayList;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.User");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Danh sách User</title>\r\n");
      out.write("<link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>\r\n");
      out.write("     <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/index.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"fontawesome-free-5.15.4-web/css/all.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"sidebar\">\r\n");
      out.write("    <div class=\"logo-details\">\r\n");
      out.write("      <i class='bx bxl-c-plus-plus icon'></i>\r\n");
      out.write("        <div class=\"logo_name\">Manager</div>\r\n");
      out.write("        <i class='bx bx-menu' id=\"btn\" ></i>\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"nav-list\">\r\n");
      out.write("      <!-- <li>\r\n");
      out.write("          <i class='bx bx-search' ></i>\r\n");
      out.write("         <form action=\"SearchStudent\" method=\"get\">\r\n");
      out.write("         	<input type=\"text\" placeholder=\"Tìm kiếm sinh viên\" name=\"key\">\r\n");
      out.write("         </form>\r\n");
      out.write("         <span class=\"tooltip\">Search</span>\r\n");
      out.write("      </li> -->\r\n");
      out.write("      \r\n");
      out.write("      <li>\r\n");
      out.write("       <a href=\"ListUser\">\r\n");
      out.write("         <i class='bx bx-user' ></i>\r\n");
      out.write("         <span class=\"links_name\">Quan ly User</span>\r\n");
      out.write("       </a>\r\n");
      out.write("       <span class=\"tooltip\">Quan ly User</span>\r\n");
      out.write("     </li>\r\n");
      out.write("     <li>\r\n");
      out.write("       <a href=\"Setting\">\r\n");
      out.write("         <i class=\"fas fa-hospital-alt\"></i>\r\n");
      out.write("         <span class=\"links_name\">Cau hinh</span>\r\n");
      out.write("       </a>\r\n");
      out.write("       <span class=\"tooltip\">Cau hinh</span>\r\n");
      out.write("     </li>\r\n");
      out.write("     <li>\r\n");
      out.write("       <a href=\"BaoCao\">\r\n");
      out.write("         <i class='bx  bx-right-arrow'></i>\r\n");
      out.write("         <span class=\"links_name\">Xuat bao cao</span>\r\n");
      out.write("       </a>\r\n");
      out.write("       <span class=\"tooltip\">Xuat bao cao</span>\r\n");
      out.write("      <!-- <li>\r\n");
      out.write("       <a href=\"ListClassRoom\">\r\n");
      out.write("         <i class=\"fas fa-hospital-alt\"></i>\r\n");
      out.write("         <span class=\"links_name\">Manage ClassRoom</span>\r\n");
      out.write("       </a>\r\n");
      out.write("       <span class=\"tooltip\">Manager ClassRoom</span>\r\n");
      out.write("     </li> -->\r\n");
      out.write("<!--      <li class=\"profile\">\r\n");
      out.write("         <div class=\"profile-details\">\r\n");
      out.write("           <img src=\"profile.jpg\" alt=\"profileImg\">\r\n");
      out.write("           <div class=\"name_job\">\r\n");
      out.write("             <div class=\"name\">Prem Shahi</div>\r\n");
      out.write("             <div class=\"job\">Web designer</div>\r\n");
      out.write("           </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <i class='bx bx-log-out' id=\"log_out\" ></i>\r\n");
      out.write("     </li> -->\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("  <section class=\"home-section\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("		      ");
 if(session.getAttribute("success")!=null)
		      			{
		      		
      out.write("\r\n");
      out.write("		      		<div class=\"alert alert-success\" role=\"alert\">\r\n");
      out.write("					  ");
      out.print(session.getAttribute("success") );
      out.write("\r\n");
      out.write("					 ");
 session.removeAttribute("success"); 
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("		      		");
} 
      out.write("\r\n");
      out.write("     		 <h1 style=\"text-align:center; padding-top:40px;\">Danh sach User</h1>\r\n");
      out.write("      		<div style=\"padding:20px 0px\">\r\n");
      out.write("      			<a class=\"btn btn-success\" href=\"AddUser\">Them User</a>\r\n");
      out.write("      		</div>\r\n");
      out.write("      		<div class=\"content\">\r\n");
      out.write("      			<table class=\"table table-dark\">\r\n");
      out.write("				  <thead>\r\n");
      out.write("				    <tr>\r\n");
      out.write("				      <th scope=\"col\">Id</th>\r\n");
      out.write("				      <th scope=\"col\">Ten</th>\r\n");
      out.write("				      <th scope=\"col\">Ma sinh vien</th>\r\n");
      out.write("				      <th scope=\"col\">Khoa</th>\r\n");
      out.write("				      <th scope=\"col\">Mat khau</th>\r\n");
      out.write("				      <th scope=\"col\">Ngay sinh</th>\r\n");
      out.write("				      <th scope=\"col\">Que quan</th>\r\n");
      out.write("				      <th scope=\"col\">Action</th>\r\n");
      out.write("				    </tr>\r\n");
      out.write("				  </thead>\r\n");
      out.write("				  <tbody>\r\n");
      out.write("				  \r\n");
      out.write("				  ");

				  ArrayList<User> listUser = (ArrayList<User>)request.getAttribute("listUser");
				  for(int i=0;i<listUser.size();i++){
      out.write("\r\n");
      out.write("				    <tr>\r\n");
      out.write("				      <th scope=\"row\">");
      out.print(listUser.get(i).getId() );
      out.write(" </th>\r\n");
      out.write("				      <td>");
      out.print(listUser.get(i).getName());
      out.write("</td>\r\n");
      out.write("				      <td>");
      out.print( listUser.get(i).getMasv() );
      out.write("</td>\r\n");
      out.write("				      ");

				      	String khoa = "";
				      	if(listUser.get(i).getKhoa()==1)
				      	{
				      		khoa = "CNTT";
				      	}else{
				      		if(listUser.get(i).getKhoa()==2)
				      		{
				      			khoa = "ATTT";
				      		}else{
				      			if(listUser.get(i).getKhoa()==3)
				      			{
				      				khoa = "DTVT";
				      			}else{
				      				if(listUser.get(i).getKhoa()==4)
				      				{
				      					khoa = "DPT";
				      				} 
				      			}
				      		}
				      	}
				      
      out.write("\r\n");
      out.write("				      <td>");
      out.print( khoa );
      out.write("</td>\r\n");
      out.write("				      <td>");
      out.print( listUser.get(i).getPassword() );
      out.write("</td>\r\n");
      out.write("				      ");
SimpleDateFormat dt1 = new SimpleDateFormat("dd/MM/yyyy"); 
      out.write("\r\n");
      out.write("				      <td>");
      out.print( dt1.format(listUser.get(i).getBirthday()));
      out.write("</td>\r\n");
      out.write("				      <td>");
      out.print( listUser.get(i).getCountry() );
      out.write("</td>\r\n");
      out.write("				      <td>\r\n");
      out.write("				      ");
				      		
				      		String urlUpdate ="UpdateUser?id="+ listUser.get(i).getId();
				      		String urlDelete ="DeleteUser?id="+ listUser.get(i).getId();
				      		String urlScore ="Score?userId="+ listUser.get(i).getId();
				      
      out.write("\r\n");
      out.write("				      		<a href=\"");
      out.print(urlUpdate);
      out.write("\" class=\"btn btn-warning\">Sua</a>\r\n");
      out.write("				      		<a href=\"");
      out.print(urlDelete);
      out.write("\" class=\"btn btn-danger\" onclick=\"return confirm('Bạn chắc chắn muốn xóa')\">Xoa</a>\r\n");
      out.write("				      		<a href=\"");
      out.print(urlScore);
      out.write("\" class=\"btn btn-info\">Bang diem</a>\r\n");
      out.write("				      </td>\r\n");
      out.write("				    </tr>\r\n");
      out.write("				    ");
} 
      out.write("\r\n");
      out.write("				  </tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("      		\r\n");
      out.write("      		</div>\r\n");
      out.write("      </div>\r\n");
      out.write("  </section>\r\n");
      out.write("  <script>\r\n");
      out.write("  let sidebar = document.querySelector(\".sidebar\");\r\n");
      out.write("  let closeBtn = document.querySelector(\"#btn\");\r\n");
      out.write("  let searchBtn = document.querySelector(\".bx-search\");\r\n");
      out.write("\r\n");
      out.write("  closeBtn.addEventListener(\"click\", ()=>{\r\n");
      out.write("    sidebar.classList.toggle(\"open\");\r\n");
      out.write("    menuBtnChange();//calling the function(optional)\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  searchBtn.addEventListener(\"click\", ()=>{ // Sidebar open when you click on the search iocn\r\n");
      out.write("    sidebar.classList.toggle(\"open\");\r\n");
      out.write("    menuBtnChange(); //calling the function(optional)\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  // following are the code to change sidebar button(optional)\r\n");
      out.write("  function menuBtnChange() {\r\n");
      out.write("   if(sidebar.classList.contains(\"open\")){\r\n");
      out.write("     closeBtn.classList.replace(\"bx-menu\", \"bx-menu-alt-right\");//replacing the iocns class\r\n");
      out.write("   }else {\r\n");
      out.write("     closeBtn.classList.replace(\"bx-menu-alt-right\",\"bx-menu\");//replacing the iocns class\r\n");
      out.write("   }\r\n");
      out.write("  }\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
